package app.tabikime.kimetabi.trip;

import java.time.LocalDate;

public record SlotResource(
        long id,
        SlotCategory category,
        String title,
        int dayFrom,
        int dayTo,
        int units,
        int sortOrder,
        SlotStatus status,
        LocalDate deadline,
        Long estPerPerson,
        Long adoptedCandidateId,
        boolean autoGenerated,
        long version
) {
}
