import type { components } from "../../api/generated/schema";

export const emptyTripPage = {
  items: [],
  nextCursor: null,
} satisfies components["schemas"]["TripPage"];

export const tokyoTripSnapshot = {
  currentMemberId: 7,
  trip: {
    id: 42,
    title: "東京の旅",
    destination: "東京",
    startsOn: "2026-09-20",
    endsOn: "2026-09-22",
    timezone: "Asia/Tokyo",
    expectedMemberCount: 3,
    phase: "PLANNING",
    phaseOverride: null,
    voteVisibility: "ANONYMOUS",
    budgetCap: null,
    revision: 1,
    version: 1,
  },
  members: [
    { id: 7, name: "わたし", role: "OWNER", status: "ACTIVE" },
    { id: 8, name: "ユイ", role: "MEMBER", status: "ACTIVE" },
    { id: 9, name: "ケン", role: "MEMBER", status: "ACTIVE" },
  ],
  slots: [
    {
      id: 101,
      category: "TRANSPORT",
      title: "往路の移動",
      dayFrom: 1,
      dayTo: 1,
      units: 1,
      sortOrder: 1,
      status: "OPEN",
      deadline: "2026-08-21",
      estPerPerson: 12000,
      adoptedCandidateId: null,
      autoGenerated: true,
      version: 1,
    },
  ],
  planItems: [],
} satisfies components["schemas"]["TripSnapshot"];

export const transportSlotDetail = {
  slot: tokyoTripSnapshot.slots[0],
  candidates: [
    {
      id: 501,
      slotId: 101,
      createdByMemberId: 7,
      title: "朝の新幹線",
      url: "https://example.com/train-a",
      imageUrl: null,
      note: "東京駅に10時着",
      tags: ["早割"],
      estAmount: 12_000,
      estBasis: "PER_PERSON",
      status: "OPEN",
      metadataStatus: "COMPLETED",
      metadataErrorCode: null,
      version: 0,
    },
    {
      id: 502,
      slotId: 101,
      createdByMemberId: 8,
      title: "ゆっくり新幹線",
      url: null,
      imageUrl: null,
      note: null,
      tags: [],
      estAmount: 30_000,
      estBasis: "TOTAL",
      status: "OPEN",
      metadataStatus: "COMPLETED",
      metadataErrorCode: null,
      version: 0,
    },
  ],
  votesByCandidate: {
    "501": {
      visibility: "ANONYMOUS",
      yesCount: 1,
      anyCount: 0,
      noCount: 0,
      unvotedMemberIds: [8, 9],
      myVote: { memberId: 7, choice: "YES", reason: null, version: 0 },
    },
    "502": {
      visibility: "ANONYMOUS",
      yesCount: 0,
      anyCount: 0,
      noCount: 0,
      unvotedMemberIds: [7, 8, 9],
      myVote: null,
    },
  },
} satisfies components["schemas"]["SlotDetail"];
