import type { components } from "../../api/generated/schema";

export const emptyTripPage = {
  items: [],
  nextCursor: null,
} satisfies components["schemas"]["TripPage"];

export const tokyoTripSnapshot = {
  trip: {
    id: 42,
    title: "東京の旅",
    destination: "東京",
    startsOn: "2026-09-20",
    endsOn: "2026-09-22",
    timezone: "Asia/Tokyo",
    expectedMemberCount: 3,
    phase: "PLANNING",
    phaseOverride: null,
    voteVisibility: "ANONYMOUS",
    budgetCap: null,
    revision: 1,
    version: 1,
  },
  members: [
    { id: 7, name: "わたし", role: "OWNER", status: "ACTIVE" },
    { id: 8, name: "ユイ", role: "MEMBER", status: "ACTIVE" },
    { id: 9, name: "ケン", role: "MEMBER", status: "ACTIVE" },
  ],
  slots: [
    {
      id: 101,
      category: "TRANSPORT",
      title: "往路の移動",
      dayFrom: 1,
      dayTo: 1,
      units: 1,
      sortOrder: 1,
      status: "OPEN",
      deadline: "2026-08-21",
      estPerPerson: 12000,
      adoptedCandidateId: null,
      autoGenerated: true,
      version: 1,
    },
  ],
} satisfies components["schemas"]["TripSnapshot"];
