CREATE TABLE settlement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    created_by_member_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    superseded_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_settlement_id_trip UNIQUE (id, trip_id),
    CONSTRAINT fk_settlement_creator FOREIGN KEY (created_by_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_settlement_version CHECK (version >= 0),
    CONSTRAINT ck_settlement_status
        CHECK (status IN ('DRAFT', 'CONFIRMED', 'COMPLETED', 'SUPERSEDED')),
    CONSTRAINT ck_settlement_status_time CHECK (
        (status = 'DRAFT' AND confirmed_at IS NULL AND completed_at IS NULL AND superseded_at IS NULL)
        OR (status = 'CONFIRMED' AND confirmed_at IS NOT NULL AND completed_at IS NULL AND superseded_at IS NULL)
        OR (status = 'COMPLETED' AND confirmed_at IS NOT NULL AND completed_at IS NOT NULL AND superseded_at IS NULL)
        OR (status = 'SUPERSEDED' AND completed_at IS NULL AND superseded_at IS NOT NULL)
    )
);

CREATE INDEX ix_settlement_trip_created ON settlement(trip_id, created_at DESC, id DESC);

CREATE TABLE settlement_expense (
    settlement_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    expense_id BIGINT NOT NULL,
    expense_version BIGINT NOT NULL,
    payer_member_id BIGINT NOT NULL,
    base_amount BIGINT NOT NULL,
    PRIMARY KEY (settlement_id, expense_id),
    CONSTRAINT fk_settlement_expense_settlement FOREIGN KEY (settlement_id, trip_id)
        REFERENCES settlement(id, trip_id) ON DELETE CASCADE,
    CONSTRAINT fk_settlement_expense_expense FOREIGN KEY (expense_id, trip_id)
        REFERENCES expense(id, trip_id),
    CONSTRAINT fk_settlement_expense_payer FOREIGN KEY (payer_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_settlement_expense_version CHECK (expense_version >= 0),
    CONSTRAINT ck_settlement_expense_amount CHECK (base_amount > 0),
    CONSTRAINT uq_settlement_expense_trip UNIQUE (settlement_id, expense_id, trip_id)
);

CREATE TABLE settlement_share (
    settlement_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    expense_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    final_amount BIGINT NOT NULL,
    PRIMARY KEY (settlement_id, expense_id, member_id),
    CONSTRAINT fk_settlement_share_expense FOREIGN KEY (settlement_id, expense_id, trip_id)
        REFERENCES settlement_expense(settlement_id, expense_id, trip_id) ON DELETE CASCADE,
    CONSTRAINT fk_settlement_share_member FOREIGN KEY (member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_settlement_share_amount CHECK (final_amount >= 0)
);

CREATE TABLE settlement_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    from_member_id BIGINT NOT NULL,
    to_member_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    paid_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_transfer_id_trip UNIQUE (id, trip_id),
    CONSTRAINT fk_transfer_settlement FOREIGN KEY (settlement_id, trip_id)
        REFERENCES settlement(id, trip_id) ON DELETE CASCADE,
    CONSTRAINT fk_transfer_from_member FOREIGN KEY (from_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT fk_transfer_to_member FOREIGN KEY (to_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_transfer_amount CHECK (amount > 0),
    CONSTRAINT ck_transfer_members CHECK (from_member_id <> to_member_id),
    CONSTRAINT ck_transfer_version CHECK (version >= 0),
    CONSTRAINT ck_transfer_status CHECK (status IN ('PENDING', 'PAID', 'CONFIRMED')),
    CONSTRAINT ck_transfer_status_time CHECK (
        (status = 'PENDING' AND paid_at IS NULL AND confirmed_at IS NULL)
        OR (status = 'PAID' AND paid_at IS NOT NULL AND confirmed_at IS NULL)
        OR (status = 'CONFIRMED' AND paid_at IS NOT NULL AND confirmed_at IS NOT NULL)
    )
);

CREATE INDEX ix_transfer_settlement ON settlement_transfer(settlement_id, status, id);
