CREATE TABLE trip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_member_id BIGINT,
    title VARCHAR(200) NOT NULL,
    destination VARCHAR(200) NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    timezone VARCHAR(40) NOT NULL,
    expected_member_count INTEGER NOT NULL,
    phase_override VARCHAR(20),
    vote_visibility VARCHAR(10) NOT NULL DEFAULT 'NAMED',
    budget_cap BIGINT,
    revision BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_trip_dates CHECK (ends_on >= starts_on),
    CONSTRAINT ck_trip_expected_member_count
        CHECK (expected_member_count BETWEEN 1 AND 100),
    CONSTRAINT ck_trip_phase_override
        CHECK (
            phase_override IS NULL
            OR phase_override IN ('PLANNING', 'TRAVELING', 'SETTLING')
        ),
    CONSTRAINT ck_trip_vote_visibility
        CHECK (vote_visibility IN ('NAMED', 'ANONYMOUS')),
    CONSTRAINT ck_trip_budget_cap CHECK (budget_cap IS NULL OR budget_cap >= 0)
);

CREATE TABLE trip_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    firebase_uid VARCHAR(128) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_trip_member_uid UNIQUE (trip_id, firebase_uid),
    CONSTRAINT uq_trip_member_id_trip UNIQUE (id, trip_id),
    CONSTRAINT ck_trip_member_role
        CHECK (role IN ('OWNER', 'ORGANIZER', 'MEMBER')),
    CONSTRAINT ck_trip_member_status
        CHECK (status IN ('ACTIVE', 'LEFT', 'REMOVED')),
    CONSTRAINT ck_trip_member_left_at
        CHECK (
            (status = 'ACTIVE' AND left_at IS NULL)
            OR (status IN ('LEFT', 'REMOVED') AND left_at IS NOT NULL)
        )
);

ALTER TABLE trip
    ADD CONSTRAINT fk_trip_owner
    FOREIGN KEY (owner_member_id, id)
    REFERENCES trip_member(id, trip_id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE UNIQUE INDEX uq_trip_active_owner
    ON trip_member(trip_id)
    WHERE role = 'OWNER' AND status = 'ACTIVE';

CREATE INDEX ix_trip_member_uid ON trip_member(firebase_uid);
CREATE INDEX ix_trip_member_active ON trip_member(trip_id, status);
CREATE INDEX ix_trip_active_updated
    ON trip(updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE idempotency_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL,
    operation VARCHAR(80) NOT NULL,
    idempotency_key UUID NOT NULL,
    request_hash CHAR(64) NOT NULL,
    response_status INTEGER,
    response_body JSONB,
    resource_type VARCHAR(40),
    resource_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_idempotency_actor_operation_key
        UNIQUE (firebase_uid, operation, idempotency_key),
    CONSTRAINT ck_idempotency_response
        CHECK (
            (
                response_status IS NULL
                AND response_body IS NULL
                AND resource_id IS NULL
            )
            OR (
                response_status BETWEEN 200 AND 499
                AND response_body IS NOT NULL
                AND resource_type IS NOT NULL
                AND resource_id IS NOT NULL
            )
        ),
    CONSTRAINT ck_idempotency_expiry CHECK (expires_at > created_at)
);

CREATE INDEX ix_idempotency_expiry ON idempotency_request(expires_at);
