CREATE TABLE slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    category VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    day_from INTEGER NOT NULL,
    day_to INTEGER NOT NULL,
    units INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    deadline DATE,
    est_per_person BIGINT,
    adopted_candidate_id BIGINT,
    auto_generated BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_slot_id_trip UNIQUE (id, trip_id),
    CONSTRAINT uq_slot_sort_order
        UNIQUE (trip_id, sort_order) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ck_slot_category
        CHECK (category IN ('LODGING', 'TRANSPORT', 'ACTIVITY', 'MEAL', 'OTHER')),
    CONSTRAINT ck_slot_days CHECK (day_from >= 1 AND day_to >= day_from),
    CONSTRAINT ck_slot_units CHECK (units >= 1),
    CONSTRAINT ck_slot_status
        CHECK (status IN ('OPEN', 'TENTATIVE', 'DECIDED', 'SKIPPED')),
    CONSTRAINT ck_slot_estimate
        CHECK (est_per_person IS NULL OR est_per_person >= 0),
    CONSTRAINT ck_slot_adoption
        CHECK (
            (status = 'DECIDED' AND adopted_candidate_id IS NOT NULL)
            OR (status <> 'DECIDED' AND adopted_candidate_id IS NULL)
        )
);

CREATE INDEX ix_slot_trip_order ON slot(trip_id, sort_order);
