CREATE TABLE invite_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    token_hash CHAR(64) NOT NULL UNIQUE,
    created_by_member_id BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_invite_id_trip UNIQUE (id, trip_id),
    CONSTRAINT fk_invite_creator
        FOREIGN KEY (created_by_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_invite_terminal_state
        CHECK (NOT (used_at IS NOT NULL AND revoked_at IS NOT NULL)),
    CONSTRAINT ck_invite_expiry CHECK (expires_at > created_at)
);

CREATE INDEX ix_invite_trip_active
    ON invite_token(trip_id, expires_at)
    WHERE used_at IS NULL AND revoked_at IS NULL;

CREATE TABLE recovery_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    member_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    created_by_member_id BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_recovery_id_trip UNIQUE (id, trip_id),
    CONSTRAINT fk_recovery_member
        FOREIGN KEY (member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT fk_recovery_creator
        FOREIGN KEY (created_by_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_recovery_terminal_state
        CHECK (NOT (used_at IS NOT NULL AND revoked_at IS NOT NULL)),
    CONSTRAINT ck_recovery_expiry CHECK (expires_at > created_at)
);

CREATE INDEX ix_recovery_trip_active
    ON recovery_token(trip_id, expires_at)
    WHERE used_at IS NULL AND revoked_at IS NULL;

CREATE TABLE token_rate_limit (
    subject_type VARCHAR(20) NOT NULL,
    subject_hash CHAR(64) NOT NULL,
    window_started_at TIMESTAMPTZ NOT NULL,
    attempt_count INTEGER NOT NULL,
    PRIMARY KEY (subject_type, subject_hash),
    CONSTRAINT ck_token_rate_limit_subject_type
        CHECK (subject_type IN ('IP', 'TOKEN')),
    CONSTRAINT ck_token_rate_limit_attempt_count CHECK (attempt_count > 0)
);

CREATE INDEX ix_token_rate_limit_window
    ON token_rate_limit(window_started_at);
