CREATE TABLE candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    slot_id BIGINT NOT NULL,
    created_by_member_id BIGINT NOT NULL,
    title VARCHAR(200),
    url TEXT,
    normalized_url TEXT,
    url_hash CHAR(64),
    image_url TEXT,
    note VARCHAR(2000),
    est_amount BIGINT,
    est_basis VARCHAR(10),
    status VARCHAR(10) NOT NULL DEFAULT 'OPEN',
    metadata_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    metadata_error_code VARCHAR(50),
    metadata_attempts INTEGER NOT NULL DEFAULT 0,
    metadata_updated_at TIMESTAMPTZ,
    title_edited_at TIMESTAMPTZ,
    image_edited_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_candidate_id_trip UNIQUE (id, trip_id),
    CONSTRAINT uq_candidate_id_trip_slot UNIQUE (id, trip_id, slot_id),
    CONSTRAINT fk_candidate_slot
        FOREIGN KEY (slot_id, trip_id) REFERENCES slot(id, trip_id),
    CONSTRAINT fk_candidate_creator
        FOREIGN KEY (created_by_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_candidate_source
        CHECK (NULLIF(BTRIM(title), '') IS NOT NULL OR url IS NOT NULL),
    CONSTRAINT ck_candidate_url_length
        CHECK (url IS NULL OR LENGTH(url) <= 2048),
    CONSTRAINT ck_candidate_image_url_length
        CHECK (image_url IS NULL OR LENGTH(image_url) <= 2048),
    CONSTRAINT ck_candidate_estimate CHECK (est_amount IS NULL OR est_amount >= 0),
    CONSTRAINT ck_candidate_estimate_pair
        CHECK (
            (est_amount IS NULL AND est_basis IS NULL)
            OR (est_amount IS NOT NULL AND est_basis IN ('PER_PERSON', 'TOTAL'))
        ),
    CONSTRAINT ck_candidate_status CHECK (status IN ('OPEN', 'REJECTED')),
    CONSTRAINT ck_candidate_metadata_status
        CHECK (metadata_status IN (
            'PENDING', 'PROCESSING', 'COMPLETED',
            'FAILED_RETRYABLE', 'FAILED_PERMANENT'
        )),
    CONSTRAINT ck_candidate_metadata_attempts CHECK (metadata_attempts >= 0)
);

ALTER TABLE slot
    ADD CONSTRAINT fk_slot_adopted_candidate
    FOREIGN KEY (adopted_candidate_id, trip_id, id)
    REFERENCES candidate(id, trip_id, slot_id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX ix_candidate_slot ON candidate(trip_id, slot_id, created_at, id);
CREATE INDEX ix_candidate_url_hash
    ON candidate(trip_id, url_hash) WHERE url_hash IS NOT NULL;
CREATE INDEX ix_candidate_metadata_pending
    ON candidate(metadata_status, updated_at)
    WHERE metadata_status IN ('PENDING', 'FAILED_RETRYABLE');

CREATE TABLE candidate_tag (
    candidate_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    tag VARCHAR(40) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (candidate_id, tag),
    CONSTRAINT fk_candidate_tag_candidate
        FOREIGN KEY (candidate_id, trip_id) REFERENCES candidate(id, trip_id),
    CONSTRAINT ck_candidate_tag_not_blank CHECK (BTRIM(tag) <> '')
);

CREATE TABLE candidate_vote (
    candidate_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    choice VARCHAR(10) NOT NULL,
    reason VARCHAR(1000),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (candidate_id, member_id),
    CONSTRAINT fk_vote_candidate
        FOREIGN KEY (candidate_id, trip_id) REFERENCES candidate(id, trip_id),
    CONSTRAINT fk_vote_member
        FOREIGN KEY (member_id, trip_id) REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_vote_choice CHECK (choice IN ('YES', 'ANY', 'NO')),
    CONSTRAINT ck_vote_reason CHECK (
        (choice = 'NO' AND reason IS NOT NULL AND BTRIM(reason) <> '')
        OR choice <> 'NO'
    )
);

CREATE INDEX ix_candidate_vote_trip_member
    ON candidate_vote(trip_id, member_id);

CREATE TABLE plan_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    slot_id BIGINT NOT NULL,
    from_candidate_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    starts_at TIMESTAMPTZ,
    timezone VARCHAR(40),
    place_ref TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_plan_item_id_trip UNIQUE (id, trip_id),
    CONSTRAINT uq_plan_item_slot UNIQUE (slot_id),
    CONSTRAINT fk_plan_item_slot
        FOREIGN KEY (slot_id, trip_id) REFERENCES slot(id, trip_id),
    CONSTRAINT fk_plan_item_candidate
        FOREIGN KEY (from_candidate_id, trip_id, slot_id)
        REFERENCES candidate(id, trip_id, slot_id)
);
