CREATE TABLE expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    plan_item_id BIGINT,
    created_by_member_id BIGINT NOT NULL,
    payer_id BIGINT,
    amount BIGINT,
    currency CHAR(3),
    base_amount BIGINT,
    paid_at TIMESTAMPTZ,
    source VARCHAR(10) NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'DRAFT',
    allocation_type VARCHAR(20),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMPTZ,
    CONSTRAINT uq_expense_id_trip UNIQUE (id, trip_id),
    CONSTRAINT fk_expense_plan_item
        FOREIGN KEY (plan_item_id, trip_id) REFERENCES plan_item(id, trip_id),
    CONSTRAINT fk_expense_creator
        FOREIGN KEY (created_by_member_id, trip_id) REFERENCES trip_member(id, trip_id),
    CONSTRAINT fk_expense_payer
        FOREIGN KEY (payer_id, trip_id) REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_expense_source CHECK (source IN ('PLAN', 'MANUAL')),
    CONSTRAINT ck_expense_status CHECK (status IN ('DRAFT', 'CONFIRMED')),
    CONSTRAINT ck_expense_amount CHECK (amount IS NULL OR amount > 0),
    CONSTRAINT ck_expense_base_amount CHECK (base_amount IS NULL OR base_amount > 0),
    CONSTRAINT ck_expense_mvp_currency CHECK (currency IS NULL OR currency = 'JPY'),
    CONSTRAINT ck_expense_confirmed CHECK (
        (status = 'DRAFT' AND confirmed_at IS NULL)
        OR (
            status = 'CONFIRMED'
            AND payer_id IS NOT NULL
            AND amount IS NOT NULL
            AND currency = 'JPY'
            AND base_amount = amount
            AND paid_at IS NOT NULL
            AND allocation_type IN ('EQUAL', 'WEIGHT', 'FIXED_AND_WEIGHT')
            AND confirmed_at IS NOT NULL
        )
    )
);

CREATE INDEX ix_expense_trip_page ON expense(trip_id, created_at DESC, id DESC);
CREATE INDEX ix_expense_trip_status ON expense(trip_id, status);

CREATE TABLE expense_share (
    expense_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    weight NUMERIC(12, 6),
    fixed_amount BIGINT,
    final_amount BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (expense_id, member_id),
    CONSTRAINT fk_share_expense
        FOREIGN KEY (expense_id, trip_id) REFERENCES expense(id, trip_id) ON DELETE CASCADE,
    CONSTRAINT fk_share_member
        FOREIGN KEY (member_id, trip_id) REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_share_weight CHECK (weight IS NULL OR weight > 0),
    CONSTRAINT ck_share_fixed_amount CHECK (fixed_amount IS NULL OR fixed_amount >= 0),
    CONSTRAINT ck_share_final_amount CHECK (final_amount IS NULL OR final_amount >= 0)
);

CREATE INDEX ix_expense_share_member ON expense_share(trip_id, member_id);

CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    actor_member_id BIGINT,
    action VARCHAR(80) NOT NULL,
    resource_type VARCHAR(40) NOT NULL,
    resource_id BIGINT NOT NULL,
    resource_version BIGINT,
    before_state JSONB,
    after_state JSONB,
    trace_id VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_actor
        FOREIGN KEY (actor_member_id, trip_id) REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_audit_state CHECK (before_state IS NOT NULL OR after_state IS NOT NULL)
);

CREATE INDEX ix_audit_trip_time
    ON audit_event(trip_id, occurred_at DESC, id DESC);
CREATE INDEX ix_audit_resource
    ON audit_event(trip_id, resource_type, resource_id, occurred_at DESC);
