-- M0-A2 implementable PostgreSQL schema proposal.
-- This is a design artifact, not a Flyway migration. M1/M2 must split it into
-- forward-only migrations after the migration number ownership is assigned.

CREATE TABLE trip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_member_id BIGINT,
    title VARCHAR(200) NOT NULL,
    destination VARCHAR(200) NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    timezone VARCHAR(40) NOT NULL,
    expected_member_count INTEGER NOT NULL,
    phase_override VARCHAR(20),
    vote_visibility VARCHAR(10) NOT NULL DEFAULT 'NAMED',
    budget_cap BIGINT,
    revision BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_trip_dates CHECK (ends_on >= starts_on),
    CONSTRAINT ck_trip_expected_member_count
        CHECK (expected_member_count > 0),
    CONSTRAINT ck_trip_phase_override
        CHECK (
            phase_override IS NULL
            OR phase_override IN ('PLANNING', 'TRAVELING', 'SETTLING')
        ),
    CONSTRAINT ck_trip_vote_visibility
        CHECK (vote_visibility IN ('NAMED', 'ANONYMOUS')),
    CONSTRAINT ck_trip_budget_cap CHECK (budget_cap IS NULL OR budget_cap >= 0)
);

CREATE TABLE trip_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    firebase_uid VARCHAR(128) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_trip_member_uid UNIQUE (trip_id, firebase_uid),
    CONSTRAINT uq_trip_member_id_trip UNIQUE (id, trip_id),
    CONSTRAINT ck_trip_member_role
        CHECK (role IN ('OWNER', 'ORGANIZER', 'MEMBER')),
    CONSTRAINT ck_trip_member_status
        CHECK (status IN ('ACTIVE', 'LEFT', 'REMOVED')),
    CONSTRAINT ck_trip_member_left_at
        CHECK (
            (status = 'ACTIVE' AND left_at IS NULL)
            OR (status IN ('LEFT', 'REMOVED') AND left_at IS NOT NULL)
        )
);

ALTER TABLE trip
    ADD CONSTRAINT fk_trip_owner
    FOREIGN KEY (owner_member_id, id)
    REFERENCES trip_member(id, trip_id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE UNIQUE INDEX uq_trip_active_owner
    ON trip_member(trip_id)
    WHERE role = 'OWNER' AND status = 'ACTIVE';

CREATE INDEX ix_trip_member_uid ON trip_member(firebase_uid);
CREATE INDEX ix_trip_member_active ON trip_member(trip_id, status);

CREATE TABLE invite_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    token_hash CHAR(64) NOT NULL UNIQUE,
    created_by_member_id BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invite_creator
        FOREIGN KEY (created_by_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_invite_terminal_state
        CHECK (NOT (used_at IS NOT NULL AND revoked_at IS NOT NULL)),
    CONSTRAINT ck_invite_expiry CHECK (expires_at > created_at)
);

CREATE INDEX ix_invite_trip_active
    ON invite_token(trip_id, expires_at)
    WHERE used_at IS NULL AND revoked_at IS NULL;

CREATE TABLE recovery_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    member_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    created_by_member_id BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recovery_member
        FOREIGN KEY (member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT fk_recovery_creator
        FOREIGN KEY (created_by_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_recovery_terminal_state
        CHECK (NOT (used_at IS NOT NULL AND revoked_at IS NOT NULL)),
    CONSTRAINT ck_recovery_expiry CHECK (expires_at > created_at)
);

CREATE INDEX ix_recovery_trip_active
    ON recovery_token(trip_id, expires_at)
    WHERE used_at IS NULL AND revoked_at IS NULL;

CREATE TABLE slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    category VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    day_from INTEGER NOT NULL,
    day_to INTEGER NOT NULL,
    units INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    deadline DATE,
    est_per_person BIGINT,
    adopted_candidate_id BIGINT,
    auto_generated BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_slot_id_trip UNIQUE (id, trip_id),
    CONSTRAINT uq_slot_sort_order
        UNIQUE (trip_id, sort_order) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ck_slot_category
        CHECK (category IN ('LODGING', 'TRANSPORT', 'ACTIVITY', 'MEAL', 'OTHER')),
    CONSTRAINT ck_slot_days CHECK (day_from >= 1 AND day_to >= day_from),
    CONSTRAINT ck_slot_units CHECK (units >= 1),
    CONSTRAINT ck_slot_status
        CHECK (status IN ('OPEN', 'TENTATIVE', 'DECIDED', 'SKIPPED')),
    CONSTRAINT ck_slot_estimate
        CHECK (est_per_person IS NULL OR est_per_person >= 0),
    CONSTRAINT ck_slot_adoption
        CHECK (
            (status = 'DECIDED' AND adopted_candidate_id IS NOT NULL)
            OR (status <> 'DECIDED' AND adopted_candidate_id IS NULL)
        )
);

CREATE INDEX ix_slot_trip_order ON slot(trip_id, sort_order);

CREATE TABLE candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    slot_id BIGINT NOT NULL,
    created_by_member_id BIGINT NOT NULL,
    title VARCHAR(200),
    url TEXT,
    normalized_url TEXT,
    url_hash CHAR(64),
    image_url TEXT,
    note VARCHAR(2000),
    est_amount BIGINT,
    est_basis VARCHAR(10),
    status VARCHAR(10) NOT NULL DEFAULT 'OPEN',
    metadata_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    metadata_error_code VARCHAR(50),
    metadata_attempts INTEGER NOT NULL DEFAULT 0,
    metadata_updated_at TIMESTAMPTZ,
    metadata_request_event_id UUID,
    title_edited_at TIMESTAMPTZ,
    image_edited_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_candidate_id_trip UNIQUE (id, trip_id),
    CONSTRAINT fk_candidate_slot
        FOREIGN KEY (slot_id, trip_id) REFERENCES slot(id, trip_id),
    CONSTRAINT fk_candidate_creator
        FOREIGN KEY (created_by_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_candidate_source CHECK (title IS NOT NULL OR url IS NOT NULL),
    CONSTRAINT ck_candidate_estimate CHECK (est_amount IS NULL OR est_amount >= 0),
    CONSTRAINT ck_candidate_estimate_pair
        CHECK (
            (est_amount IS NULL AND est_basis IS NULL)
            OR (
                est_amount IS NOT NULL
                AND est_basis IN ('PER_PERSON', 'TOTAL')
            )
        ),
    CONSTRAINT ck_candidate_status CHECK (status IN ('OPEN', 'REJECTED')),
    CONSTRAINT ck_candidate_metadata_status
        CHECK (
            metadata_status IN (
                'PENDING',
                'PROCESSING',
                'COMPLETED',
                'FAILED_RETRYABLE',
                'FAILED_PERMANENT'
            )
        ),
    CONSTRAINT ck_candidate_metadata_attempts CHECK (metadata_attempts >= 0)
);

ALTER TABLE slot
    ADD CONSTRAINT fk_slot_adopted_candidate
    FOREIGN KEY (adopted_candidate_id, trip_id)
    REFERENCES candidate(id, trip_id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX ix_candidate_slot ON candidate(trip_id, slot_id, created_at);
CREATE INDEX ix_candidate_url_hash
    ON candidate(trip_id, url_hash)
    WHERE url_hash IS NOT NULL;
CREATE INDEX ix_candidate_metadata_pending
    ON candidate(metadata_status, updated_at)
    WHERE metadata_status IN ('PENDING', 'FAILED_RETRYABLE');
CREATE INDEX ix_candidate_metadata_request_event
    ON candidate(metadata_request_event_id)
    WHERE metadata_request_event_id IS NOT NULL;

CREATE TABLE candidate_tag (
    candidate_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    tag VARCHAR(40) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (candidate_id, tag),
    CONSTRAINT fk_candidate_tag_candidate
        FOREIGN KEY (candidate_id, trip_id)
        REFERENCES candidate(id, trip_id),
    CONSTRAINT ck_candidate_tag_not_blank CHECK (BTRIM(tag) <> '')
);

CREATE TABLE candidate_vote (
    candidate_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    choice VARCHAR(10) NOT NULL,
    reason VARCHAR(1000),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (candidate_id, member_id),
    CONSTRAINT fk_vote_candidate
        FOREIGN KEY (candidate_id, trip_id)
        REFERENCES candidate(id, trip_id),
    CONSTRAINT fk_vote_member
        FOREIGN KEY (member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_vote_choice CHECK (choice IN ('YES', 'ANY', 'NO')),
    CONSTRAINT ck_vote_reason
        CHECK (
            (choice = 'NO' AND reason IS NOT NULL AND BTRIM(reason) <> '')
            OR choice <> 'NO'
        )
);

CREATE INDEX ix_candidate_vote_trip_member
    ON candidate_vote(trip_id, member_id);

CREATE TABLE plan_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    slot_id BIGINT NOT NULL,
    from_candidate_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    starts_at TIMESTAMPTZ,
    timezone VARCHAR(40),
    place_ref TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_plan_item_id_trip UNIQUE (id, trip_id),
    CONSTRAINT uq_plan_item_slot UNIQUE (slot_id),
    CONSTRAINT fk_plan_item_slot
        FOREIGN KEY (slot_id, trip_id) REFERENCES slot(id, trip_id),
    CONSTRAINT fk_plan_item_candidate
        FOREIGN KEY (from_candidate_id, trip_id)
        REFERENCES candidate(id, trip_id)
);

CREATE TABLE expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    plan_item_id BIGINT,
    created_by_member_id BIGINT NOT NULL,
    payer_id BIGINT,
    amount BIGINT,
    currency CHAR(3),
    base_amount BIGINT,
    paid_at TIMESTAMPTZ,
    source VARCHAR(10) NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'DRAFT',
    allocation_type VARCHAR(20),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMPTZ,
    CONSTRAINT uq_expense_id_trip UNIQUE (id, trip_id),
    CONSTRAINT fk_expense_plan_item
        FOREIGN KEY (plan_item_id, trip_id)
        REFERENCES plan_item(id, trip_id),
    CONSTRAINT fk_expense_creator
        FOREIGN KEY (created_by_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT fk_expense_payer
        FOREIGN KEY (payer_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_expense_source CHECK (source IN ('PLAN', 'MANUAL')),
    CONSTRAINT ck_expense_status CHECK (status IN ('DRAFT', 'CONFIRMED')),
    CONSTRAINT ck_expense_mvp_currency
        CHECK (currency IS NULL OR currency = 'JPY'),
    CONSTRAINT ck_expense_confirmed
        CHECK (
            (status = 'DRAFT' AND confirmed_at IS NULL)
            OR (
                status = 'CONFIRMED'
                AND payer_id IS NOT NULL
                AND amount IS NOT NULL
                AND amount > 0
                AND currency = 'JPY'
                AND base_amount IS NOT NULL
                AND base_amount = amount
                AND paid_at IS NOT NULL
                AND allocation_type IN ('EQUAL', 'WEIGHT', 'FIXED_AND_WEIGHT')
                AND confirmed_at IS NOT NULL
            )
        )
);

CREATE INDEX ix_expense_trip_page
    ON expense(trip_id, created_at DESC, id DESC);
CREATE INDEX ix_expense_trip_status ON expense(trip_id, status);

CREATE TABLE expense_receipt (
    id UUID PRIMARY KEY,
    expense_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    object_key VARCHAR(500) NOT NULL UNIQUE,
    content_type VARCHAR(20) NOT NULL,
    byte_size BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    uploaded_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    CONSTRAINT fk_receipt_expense
        FOREIGN KEY (expense_id, trip_id)
        REFERENCES expense(id, trip_id),
    CONSTRAINT ck_receipt_content_type
        CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp')),
    CONSTRAINT ck_receipt_byte_size CHECK (byte_size > 0 AND byte_size <= 10485760),
    CONSTRAINT ck_receipt_status
        CHECK (status IN ('PENDING', 'UPLOADED', 'FAILED')),
    CONSTRAINT ck_receipt_status_time
        CHECK (
            (status = 'PENDING' AND uploaded_at IS NULL AND failed_at IS NULL)
            OR (status = 'UPLOADED' AND uploaded_at IS NOT NULL AND failed_at IS NULL)
            OR (status = 'FAILED' AND uploaded_at IS NULL AND failed_at IS NOT NULL)
        )
);

CREATE INDEX ix_receipt_expense ON expense_receipt(trip_id, expense_id);
CREATE INDEX ix_receipt_orphan_cleanup
    ON expense_receipt(created_at)
    WHERE status IN ('PENDING', 'FAILED');

CREATE TABLE expense_share (
    expense_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    weight NUMERIC(12, 6),
    fixed_amount BIGINT,
    final_amount BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (expense_id, member_id),
    CONSTRAINT fk_share_expense
        FOREIGN KEY (expense_id, trip_id)
        REFERENCES expense(id, trip_id),
    CONSTRAINT fk_share_member
        FOREIGN KEY (member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_share_weight CHECK (weight IS NULL OR weight > 0),
    CONSTRAINT ck_share_fixed_amount
        CHECK (fixed_amount IS NULL OR fixed_amount >= 0),
    CONSTRAINT ck_share_final_amount
        CHECK (final_amount IS NULL OR final_amount >= 0)
);

CREATE INDEX ix_expense_share_member ON expense_share(trip_id, member_id);

CREATE TABLE settlement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    created_by_member_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    superseded_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_settlement_id_trip UNIQUE (id, trip_id),
    CONSTRAINT fk_settlement_creator
        FOREIGN KEY (created_by_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_settlement_status
        CHECK (status IN ('DRAFT', 'CONFIRMED', 'COMPLETED', 'SUPERSEDED')),
    CONSTRAINT ck_settlement_status_time
        CHECK (
            (
                status = 'DRAFT'
                AND confirmed_at IS NULL
                AND completed_at IS NULL
                AND superseded_at IS NULL
            )
            OR (
                status = 'CONFIRMED'
                AND confirmed_at IS NOT NULL
                AND completed_at IS NULL
                AND superseded_at IS NULL
            )
            OR (
                status = 'COMPLETED'
                AND confirmed_at IS NOT NULL
                AND completed_at IS NOT NULL
                AND superseded_at IS NULL
            )
            OR (
                status = 'SUPERSEDED'
                AND completed_at IS NULL
                AND superseded_at IS NOT NULL
            )
        )
);

CREATE INDEX ix_settlement_trip_created
    ON settlement(trip_id, created_at DESC);

CREATE TABLE settlement_expense (
    settlement_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    expense_id BIGINT NOT NULL,
    expense_version BIGINT NOT NULL,
    payer_member_id BIGINT NOT NULL,
    base_amount BIGINT NOT NULL,
    PRIMARY KEY (settlement_id, expense_id),
    CONSTRAINT fk_settlement_expense_settlement
        FOREIGN KEY (settlement_id, trip_id)
        REFERENCES settlement(id, trip_id),
    CONSTRAINT fk_settlement_expense_expense
        FOREIGN KEY (expense_id, trip_id)
        REFERENCES expense(id, trip_id),
    CONSTRAINT fk_settlement_expense_payer
        FOREIGN KEY (payer_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_settlement_expense_amount CHECK (base_amount > 0),
    CONSTRAINT uq_settlement_expense_trip
        UNIQUE (settlement_id, expense_id, trip_id)
);

CREATE TABLE settlement_share (
    settlement_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    expense_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    final_amount BIGINT NOT NULL,
    PRIMARY KEY (settlement_id, expense_id, member_id),
    CONSTRAINT fk_settlement_share_expense
        FOREIGN KEY (settlement_id, expense_id, trip_id)
        REFERENCES settlement_expense(settlement_id, expense_id, trip_id),
    CONSTRAINT fk_settlement_share_member
        FOREIGN KEY (member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_settlement_share_amount CHECK (final_amount >= 0)
);

CREATE TABLE settlement_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    from_member_id BIGINT NOT NULL,
    to_member_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    paid_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_transfer_id_trip UNIQUE (id, trip_id),
    CONSTRAINT fk_transfer_settlement
        FOREIGN KEY (settlement_id, trip_id)
        REFERENCES settlement(id, trip_id),
    CONSTRAINT fk_transfer_from_member
        FOREIGN KEY (from_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT fk_transfer_to_member
        FOREIGN KEY (to_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_transfer_amount CHECK (amount > 0),
    CONSTRAINT ck_transfer_members CHECK (from_member_id <> to_member_id),
    CONSTRAINT ck_transfer_status
        CHECK (status IN ('PENDING', 'PAID', 'CONFIRMED')),
    CONSTRAINT ck_transfer_status_time
        CHECK (
            (status = 'PENDING' AND paid_at IS NULL AND confirmed_at IS NULL)
            OR (status = 'PAID' AND paid_at IS NOT NULL AND confirmed_at IS NULL)
            OR (status = 'CONFIRMED' AND paid_at IS NOT NULL AND confirmed_at IS NOT NULL)
        )
);

CREATE INDEX ix_transfer_settlement
    ON settlement_transfer(settlement_id, status);

CREATE TABLE settlement_source_transfer (
    settlement_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    source_transfer_id BIGINT NOT NULL,
    source_transfer_version BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    PRIMARY KEY (settlement_id, source_transfer_id),
    CONSTRAINT fk_source_transfer_settlement
        FOREIGN KEY (settlement_id, trip_id)
        REFERENCES settlement(id, trip_id),
    CONSTRAINT fk_source_transfer_transfer
        FOREIGN KEY (source_transfer_id, trip_id)
        REFERENCES settlement_transfer(id, trip_id),
    CONSTRAINT ck_source_transfer_amount CHECK (amount > 0),
    CONSTRAINT ck_source_transfer_status CHECK (status IN ('PAID', 'CONFIRMED'))
);

CREATE TABLE idempotency_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL,
    operation VARCHAR(80) NOT NULL,
    idempotency_key UUID NOT NULL,
    request_hash CHAR(64) NOT NULL,
    response_status INTEGER,
    response_body JSONB,
    resource_type VARCHAR(40),
    resource_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_idempotency_actor_operation_key
        UNIQUE (firebase_uid, operation, idempotency_key),
    CONSTRAINT ck_idempotency_response
        CHECK (
            (response_status IS NULL AND response_body IS NULL)
            OR (
                response_status IS NOT NULL
                AND response_status BETWEEN 200 AND 499
                AND response_body IS NOT NULL
            )
        ),
    CONSTRAINT ck_idempotency_expiry CHECK (expires_at > created_at)
);

CREATE INDEX ix_idempotency_expiry ON idempotency_request(expires_at);

CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    actor_member_id BIGINT,
    action VARCHAR(80) NOT NULL,
    resource_type VARCHAR(40) NOT NULL,
    resource_id BIGINT NOT NULL,
    resource_version BIGINT,
    before_state JSONB,
    after_state JSONB,
    trace_id VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_actor
        FOREIGN KEY (actor_member_id, trip_id)
        REFERENCES trip_member(id, trip_id),
    CONSTRAINT ck_audit_state CHECK (before_state IS NOT NULL OR after_state IS NOT NULL)
);

CREATE INDEX ix_audit_trip_time
    ON audit_event(trip_id, occurred_at DESC, id DESC);
CREATE INDEX ix_audit_resource
    ON audit_event(trip_id, resource_type, resource_id, occurred_at DESC);

CREATE TABLE outbox_event (
    id UUID PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trip(id),
    trip_revision BIGINT NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    resource_type VARCHAR(40) NOT NULL,
    resource_id BIGINT NOT NULL,
    resource_version BIGINT,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_outcome_code VARCHAR(50),
    CONSTRAINT ck_outbox_attempts CHECK (attempts >= 0)
);

ALTER TABLE candidate
    ADD CONSTRAINT fk_candidate_metadata_request_event
    FOREIGN KEY (metadata_request_event_id) REFERENCES outbox_event(id);

CREATE INDEX ix_outbox_trip_revision
    ON outbox_event(trip_id, trip_revision);
CREATE INDEX ix_outbox_unpublished
    ON outbox_event(created_at)
    WHERE published_at IS NULL;

-- Rules that require transaction-aware validation and therefore remain in the
-- domain service (with integration tests), rather than CHECK constraints:
-- 1. Exactly one ACTIVE OWNER exists after each committed trip update.
-- 2. slot.adopted_candidate_id belongs to that exact slot, not only the trip.
-- 3. A CONFIRMED expense has at least one share and sum(final_amount)=base_amount.
-- 4. allocation_type matches the allowed weight/fixed_amount shape.
-- 5. A settlement snapshot's expense/share amounts balance, and confirmed
--    settlements plus their snapshots are immutable.
-- 6. Audit state and idempotency response bodies redact tokens and signed URLs.
